import { BigNumber } from 'ethers';

// @utils
import { parseEther } from '@utils/blockchain';

export const MINUTE = 60;
export const HOUR = 60 * MINUTE;
export const DAY = 24 * HOUR;

export const Constant = {
    // Common
    COMMON_RATE_DECIMALS: 18,
    COMMON_RATE_MAX_FRACTION: parseEther('1'),
    COMMON_INFINITE_TIMESTAMP: BigNumber.from(2).pow(40).sub(1),

    // Admin
    ADMIN_NUMBER: 5,
    ADMIN_SIGNATURE_VERIFICATION_QUORUM: 4,

    // Estate Token
    ESTATE_TOKEN_CONFIRMATION_TIME_LIMIT: 30 * DAY,
    ESTATE_TOKEN_TOKEN_DECIMALS: 18,

    // Estate Forger
    ESTATE_FORGER_MINIMUM_SALE_DURATION: 30 * DAY,
    ESTATE_FORGER_CONFIRMATION_TIME_LIMIT: 30 * DAY,

    // Estate Liquidator
    ESTATE_LIQUIDATOR_UNANIMOUS_GUARD_DURATION: 365 * DAY,
    ESTATE_LIQUIDATOR_UNANIMOUS_QUORUM_RATE: parseEther('1'),
    ESTATE_LIQUIDATOR_MAJORITY_QUORUM_RATE: parseEther('0.75'),

    ESTATE_LIQUIDATOR_VOTING_DURATION: 30 * DAY,
    ESTATE_LIQUIDATOR_DIVIDEND_ISSUANCE_DATA: 'LIQUIDATED',

    // Project Token
    PROJECT_TOKEN_MAX_DECIMALS: 18,

    // Prestige Pad
    PRESTIGE_PAD_RAISE_MINIMUM_DURATION: 7 * DAY,
    PRESTIGE_PAD_RAISE_CONFIRMATION_TIME_LIMIT: 30 * DAY,

    // Primary Token
    PRIMARY_TOKEN_BASE_DISCOUNT: parseEther('0.15'),

    PRIMARY_TOKEN_MAXIMUM_SUPPLY: parseEther(String(20_000_000_000)),
    PRIMARY_TOKEN_BACKER_ROUND: parseEther(String(100_000_000)),
    PRIMARY_TOKEN_CORE_TEAM: parseEther(String(1_000_000_000)),
    PRIMARY_TOKEN_EXTERNAL_TREASURY: parseEther(String(1_000_000_000)),
    PRIMARY_TOKEN_MARKET_MAKER: parseEther(String(2_270_000_000)),
    PRIMARY_TOKEN_PRIVATE_SALE_1: parseEther(String(30_000_000)),
    PRIMARY_TOKEN_PRIVATE_SALE_2: parseEther(String(50_000_000)),
    PRIMARY_TOKEN_PUBLIC_SALE: parseEther(String(500_000_000)),
    PRIMARY_TOKEN_SEED_ROUND: parseEther(String(50_000_000)),

    PRIMARY_TOKEN_STAKE_1_WAVE_REWARD: parseEther(String(2_000_000)),
    PRIMARY_TOKEN_STAKE_2_WAVE_REWARD: parseEther(String(3_000_000)),
    PRIMARY_TOKEN_STAKE_3_WAVE_REWARD: parseEther(String(4_000_000)),

    PRIMARY_TOKEN_STAKE_1_CULMINATING_WAVE: 750,
    PRIMARY_TOKEN_STAKE_2_CULMINATING_WAVE: 1500,
    PRIMARY_TOKEN_STAKE_3_CULMINATING_WAVE: 2250,

    // Stake Token
    STAKE_TOKEN_REWARD_FETCH_COOLDOWN: DAY - 5 * MINUTE,

    // Treasury
    TREASURY_OPERATION_FUND_RATE: parseEther('0.2'),

    // Governance Hub
    GOVERNANCE_HUB_CONFIRMATION_TIME_LIMIT: 30 * DAY,
};
